### ISSUE TITLE
Missing ability icons from Arena (early 2023)

### ISSUE THREAD

**Issue by ThePieBandit** [andrewgioia/mana#94]
The following arena icons seem to be missing.
- can't block/must attack
- stun
- commanders (substitute for legendary supertype)
- Not sure if there is an icon, but decayed
- flashback
- Goad (not on arena, that I know, but was printed on some punch outs for a commander deck)
- cleave
- changeling
- prototype

**Comment by TinyShopkeep** [comment]
The new ones from Capenna aren't here either, Shield, ect. Also a Prototype token would be great

**Comment by ThePieBandit** [comment]
@TinyShopkeep if you want a prototype reminder, I did design one, you can grab it here: https://www.thingiverse.com/thing:5657655

@andrewgioia is there anything we can do to streamline the process of getting icons from newer sets into the mana font?

**Comment by andrewgioia** [comment]
@ThePieBandit thanks so much for this list, is it all possible to do a full roundup on what's missing? I plan to get to this and then start adding them shortly and that would be an immense time saver.

**Comment by andrewgioia** [comment]
Work in progress compilation, will update main issue with this once it's compleat (;P). Bold need icons, regular text are the abilities that exist but do not have symbols in-game.

* ONE
   * **For Mirrodin**
   * x Toxic: uses a drop and has color, could add this but deferring for now
   * x Corrupted
* BRO
   * **Prototype**
   * **Meld**
   * **Unearth**
   * **Stun**
* DMU
   * **Enlist**
   * **Read Ahead**
   * x Kicker
* SNC
   * **Casualty**
   * **Shield counter**
   * **Hideaway**
   * **Blitz**
   * x Alliance
* NEO
   * **Ninjutsu**
   * **Reconfigure**
   * x Channel

[ . . . ]

**Comment by ThePieBandit** [comment]
Extracting what I could from the data files, which is buggy as hell, here is the full list of abilities I was able to find. Note that some seem to be named after their faction as opposed to the mechanic. (i.e., Maestros, not casualty)

Regarding your list, I noticed decayed actually has an icon. it's not visible in the deck builder (for some reason) but it does show up in game. you can see it rendered here: https://mtg.fandom.com/wiki/Decayed

```
Icon_Keyword_Changeling
Icon_Keyword_Count_Large
Icon_Keyword_Defender
Icon_Keyword_Flash
Icon_Keyword_Haste
Icon_Keyword_Prowess
Icon_Primary_Deathtouch
Icon_Primary_DoubleStrike
Icon_Primary_FirstStrike
Icon_Primary_Indestructible
Icon_Primary_Lifelink
Icon_Primary_Menace
Icon_Primary_Reach
Icon_Primary_Trample
Icon_Primary_Vigilance
Icon_Secondary_Flying
Icon_Secondary_Hexproof_Disabled
Icon_Secondary_Hexproof
Keyword_Icon_DefenderCrossout
Triggered_Icon_Convoke
Icon_Keyword_Aftermath
Icon_Keyword_Daybound_Nightbound
Icon_Keyword_Decayed
Icon_Keyword_Exploit
Icon_Keyword_Haktos
Icon_Keyword_Improvise
Icon_Keyword_Training
Icon_Keyword_ValueProtection_Even_IKO
Icon_Keyword_ValueProtection_Odd_IKO
Icon_Keyword_Ward
Icon_Secondary_HexproofB
Icon_Secondary_HexproofG
Icon_Secondary_HexproofR
Icon_Secondary_HexproofU
Icon_Secondary_HexproofW
Triggered_Icon_Adapt
Triggered_Icon_Ascend
Triggered_Icon_JumpStart
Triggered_Icon_Mentor
Triggered_Icon_Riot
Icon_Keyword_Afflict
Icon_Keyword_Channel
Icon_Keyword_Cleave
Icon_Keyword_Companion
Icon_Keyword_DayNight
Icon_Keyword_Escape
Icon_Keyword_Fabricate
Icon_Keyword_Flashback
Icon_Keyword_Foretell
Icon_Keyword_Hideaway
Icon_Keyword_Kicker
Icon_Keyword_Maestros
Icon_Keyword_Mutate
Icon_Keyword_Ninjutsu
Icon_Keyword_Reconfigure
Icon_Keyword_Riveteers
Icon_Keyword_VentureIntoTheDungeon
Triggered_Icon_Afterlife
Triggered_Icon_Constellation
Triggered_Icon_Spectacle
Icon_Keyword_Adamant
Icon_Keyword_Amass
Icon_Keyword_Cabaretti
Icon_Keyword_Coven
Icon_Keyword_Devotion
Icon_Keyword_Embalm
Icon_Keyword_Eternalyze
Icon_Keyword_Investigate
Icon_Keyword_Landfall
Icon_Keyword_Learn
Icon_Keyword_Magecraft
Icon_Keyword_Party
Icon_Keyword_Revolt
Icon_Keyword_ShieldCounters
Triggered_Icon_Addendum
Triggered_Icon_Enrage
Triggered_Icon_Explore
Triggered_Icon_Raid
Triggered_Icon_Surveil
Triggered_Icon_Undergrowth
Icon_DMU_Domain
Icon_Keyword_Disturb
Icon_Keyword_DoubleTeam
Icon_Keyword_Enlist
Icon_Keyword_Hexproof
Icon_Keyword_Meld
Icon_Keyword_Obscura
Icon_Keyword_Phyrexian
Icon_Keyword_Proliferate
Icon_Keyword_Prototype
Icon_Keyword_Quandrix
Icon_Keyword_ReadAhead
Icon_Keyword_RollAD20
Icon_Keyword_Specialize
Icon_Keyword_StunCounters
Icon_Keyword_Unearth
Icon_Special_Tap
Keyword_Icon_Hexproof_Crossout
manapool_poison
snowHangerIcon
Icon_Keyword_ForMirrodin
Icon_Keyword_Toxic
Icon_ONE_Corrupted
```

**Comment by ThePieBandit** [comment]
Please consider adding Toxic sooner rather than later, as you can create tokens with toxic it'll be a handy one to have.

**Comment by andrewgioia** [comment]
Thanks @ThePieBandit this is extremely helpful. Are you able to extract the images from those asset files/bundles? I have a windows machine I can try on but curious if you’ve tried.

**Comment by ThePieBandit** [comment]
I tried....but I failed. And I'm pretty sure trying to install unity on my machine to view them messed up my machine. I'm on Linux, FWIW. Ironically, magic arena has some sort of horrible graphical issue now that makes it unplayable.

I got these files from /drive_c/Program Files/Wizards of the Coast/MTGA/MTGA_Data/Downloads/AssetBundle, specifically, the files that start with `Bucket_Ability.BadgeEntry_`

**Comment by andrewgioia** [comment]
Thanks @ThePieBandit! I see the same set in the assetbundles. 

They unfortunately are extremely low-res and not much better, if at all, from screenshots I can take in Arena, but they're helping at least and it's nice to see the full set.

**Comment by andrewgioia** [comment]
I'm not sure unfortunately, all I'm able to do is export PNGs from the texture files in those assetbundles, and I'm using [UABE](https://github.com/SeriousCache/UABE) to do it as I have no experience with Unity. 

I installed Unity to try to import these bundles but couldn't figure it out, if you could point me to something I'm happy to try there again though.

**Comment by ThePieBandit** [comment]
Unfortunately I'm in the same boat as you here. I don't have unity experience, and the extractor you linked didn't work on my Linux machine.

**Comment by ThePieBandit** [comment]
FYI, here's the contents of the Asset files I was able to extract using [AssetRipper](https://assetripper.github.io/AssetRipper/index.html)

```
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!213 &21300000
Sprite:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_Name: Icon_Keyword_Aftermath
  m_Rect:
    serializedVersion: 2
    x: 0
    y: 0
    width: 0
    height: 0
  m_Offset: {x: NaN, y: NaN}
  m_PixelsToUnits: 0
  m_Extrude: 0
  m_AtlasName:
  m_PackingTag:
  m_RD:
    texture: {fileID: 0}
    vertices:
    - pos: {x: 0.5, y: 0.5, z: 1E-45}
      uv: {x: 0, y: -1.610709E+16}
    - pos: {x: 933938940, y: -1.3780004E-06, z: -64457004}
      uv: {x: 3.6185428E-38, y: 0}
    - pos: {x: 0, y: 0, z: 0}
      uv: {x: 0, y: 0}
    - pos: {x: 3.862209E+11, y: -1.09623995E-32, z: 0}
      uv: {x: 0, y: 0}
    - pos: {x: 0, y: 1E-45, z: 0}
      uv: {x: 4.2E-44, y: 0}
    - pos: {x: 0, y: 0, z: 1.7E-44}
      uv: {x: 0, y: 0}
    - pos: {x: 0, y: 0, z: 0}
      uv: {x: 0, y: 8.4E-44}
    - pos: {x: 9.1837E-40, y: 7.34697E-40, z: 9.18368E-40}
      uv: {x: 8.26529E-40, y: 5.51024E-40}
    - pos: {x: 7.34694E-40, y: 6.42854E-40, z: 4.59186E-40}
      uv: {x: 5.51019E-40, y: 3.67342E-40}
    - pos: {x: 2.75513E-40, y: 6E-45, z: 2.75508E-40}
      uv: {x: 1.83671E-40, y: 1E-45}
    - pos: {x: 1.7E-44, y: 2E-44, z: 3.761582E-37}
      uv: {x: 0, y: 0}
    - pos: {x: 0, y: 9.403956E-38, z: 0}
      uv: {x: 0, y: 0}
    - pos: {x: 0, y: 0, z: 0}
      uv: {x: 0, y: 0}
    - pos: {x: 0, y: 3.36E-43, z: 0.31}
      uv: {x: -0.11, y: 0}
    - pos: {x: 0.32, y: -0.2, z: 0}
      uv: {x: 0.32, y: -0.13}
    - pos: {x: 0, y: 0.3, z: -0.21}
      uv: {x: 0, y: 0.13}
    - pos: {x: -0.28, y: 0, z: 0.07}
      uv: {x: 0.3, y: 0}
    - pos: {x: -0.01, y: 0.3, z: 0}
      uv: {x: -0.06, y: -0.28}
    - pos: {x: 0, y: -0.07, z: 0.27}
      uv: {x: 0, y: -0.16}
    - pos: {x: -0.27, y: 0, z: -0.32}
      uv: {x: -0.14, y: 0}
    - pos: {x: -0.32, y: -0.23, z: 0}
      uv: {x: 0, y: 0}
    - pos: {x: 0, y: 0, z: 0}
      uv: {x: 0, y: 0}
    - pos: {x: 0, y: 0, z: 0}
      uv: {x: 0, y: 0}
    - pos: {x: 0, y: 0, z: 0}
      uv: {x: 0, y: 0}
    - pos: {x: 0, y: 0, z: 0}
      uv: {x: 0, y: 0}
    - pos: {x: 0, y: 0, z: 0}
      uv: {x: 0, y: 4.026751}
    - pos: {x: 64, y: 57.897125, z: 0}
      uv: {x: 4.026751, y: -1}
    - pos: {x: -1, y: 9E-44, z: 100}
      uv: {x: 32, y: 100}
    - pos: {x: 32, y: 1, z: 1E-45}
      uv: {x: 2.4E-44, y: 0.11}
    - pos: {x: -0.25, y: 0.31, z: -0.21}
      uv: {x: 0.32, y: -0.19}
    - pos: {x: 0.32, y: -0.13, z: 0.04}
      uv: {x: 0.29, y: 0}
    - pos: {x: 0.29, y: -0.07, z: 0.19999999}
      uv: {x: -0.31, y: -0.13}
    - pos: {x: -0.32, y: -0.16, z: -0.32}
      uv: {x: -0.19, y: -0.31}
    - pos: {x: -0.19999999, y: -0.14999999, z: -0.26}
      uv: {x: -0.099999994, y: -0.28}
    - pos: {x: 0.089999996, y: -0.28, z: 0.099999994}
      uv: {x: -0.26, y: 0.099999994}
    indices: []
    textureRect:
      serializedVersion: 2
      x: 0
      y: 0
      width: 0
      height: 0
    textureRectOffset: {x: 0, y: 0}
    settingsRaw: 0
```
